name: CI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "develop-BE" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./be"

    steps:
      - uses: actions/checkout@v3
      
      - name: Set application.yml for deploy
        working-directory: ./be/src/main/resources
        run: |
          echo "${{ secrets.APPLICATION }}" >> ./application-prod.yml
          cat application-prod.yml

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'
                
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: issuetracker
          mysql user: root
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew bootJar 

	      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          
      - name: Docker build
        run: |
          docker build -t issue-tracker .
          docker tag issue-tracker ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracker:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracker:${GITHUB_SHA::7}
          
      - name: deploy!
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
		    sudo docker ps -a -q -f "name=issue-tracker" | grep -q . && docker stop issue-tracker && docker rm issue-tracker | true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracker:${GITHUB_SHA::7}
            sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/issue-trakcer:${GITHUB_SHA::7} issue-tracker
            sudo docker run -d -e --name issue-tracker -p 80:8080 issue-tracker
